# Generated by Django 5.0.2 on 2024-03-01 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('academicId', models.AutoField(primary_key=True, serialize=False)),
                ('forename', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('specialty', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='keywords',
            field=models.CharField(choices=[('AI', 'Artificial Intelligence'), ('ML', 'Machine Learning'), ('SE', 'Software Engineering'), ('DS', 'Data Science'), ('CS', 'Cyber Security'), ('IS', 'Information Systems'), ('CG', 'Computer Graphics'), ('HCI', 'Human Computer Interaction'), ('CV', 'Computer Vision'), ('NLP', 'Natural Language Processing')], default='select', max_length=50),
        ),
        migrations.CreateModel(
            name='Bridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.FloatField()),
                ('academicId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marking.academic')),
                ('urn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marking.student')),
            ],
        ),
        migrations.AddConstraint(
            model_name='bridge',
            constraint=models.UniqueConstraint(fields=('urn', 'id'), name='unique_bridge'),
        ),
    ]
