# Generated by Django 5.0.2 on 2024-03-03 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marking', '0002_academic_student_keywords_bridge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convener',
            fields=[
                ('convenerId', models.AutoField(primary_key=True, serialize=False)),
                ('forename', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Moderation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalMark', models.FloatField()),
                ('comment', models.TextField()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='bridge',
            name='unique_bridge',
        ),
        migrations.RemoveField(
            model_name='bridge',
            name='academicId',
        ),
        migrations.RemoveField(
            model_name='bridge',
            name='mark',
        ),
        migrations.AddField(
            model_name='bridge',
            name='academic1',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='academic1', to='marking.academic'),
        ),
        migrations.AddField(
            model_name='bridge',
            name='academic2',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='academic2', to='marking.academic'),
        ),
        migrations.AddField(
            model_name='bridge',
            name='comment',
            field=models.TextField(default='Add comment'),
        ),
        migrations.AddField(
            model_name='bridge',
            name='mark1',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='bridge',
            name='mark2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddConstraint(
            model_name='bridge',
            constraint=models.UniqueConstraint(fields=('urn', 'academic1'), name='unique_bridge_academic1'),
        ),
        migrations.AddConstraint(
            model_name='bridge',
            constraint=models.UniqueConstraint(fields=('urn', 'academic2'), name='unique_bridge_academic2'),
        ),
        migrations.AddField(
            model_name='convener',
            name='academic1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic1_convener', to='marking.academic'),
        ),
        migrations.AddField(
            model_name='convener',
            name='academic2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic2_convener', to='marking.academic'),
        ),
        migrations.AddField(
            model_name='convener',
            name='selected_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_by_convener', to='marking.student'),
        ),
        migrations.AddField(
            model_name='moderation',
            name='urn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_entry', to='marking.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='moderation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_entry', to='marking.moderation'),
        ),
    ]
